### ISSUE TITLE
e2e test scenario

### ISSUE THREAD

**Issue by roberts-ivanovs** [eigerco/axelar-amplifier#2]
I will try creating a new integration test that will actually use ampd to talk to the axelar contracts. Not sure how it'll go, but I need to play around with the actual code to understand how much of an undertaking this is.

with the current test setup that they have, it's not possible to spin up the "axelar test node", because it's not even a node, but an emulation that they run [[cw-multi-test]](https://github.com/CosmWasm/cw-multi-test)
> Multitest is a design to simulate a blockchain environment in pure Rust. This allows us to run unit tests that involve contract -> contract, and contract -> bank interactions. This is not intended to be a full blockchain app but to simulate the Cosmos SDK x/wasm module close enough to gain confidence in multi-contract deployments before testing them on a live blockchain.

While this is fine for testing the wasm contracts, it is not enough for testing ampd - we need a grpc port to bind to. I will see if I can spin up a an [axelar node](https://github.com/axelarnetwork/axelar-core) using [testcontainers](https://github.com/testcontainers/testcontainers-rs) (edited)

Currently the path I am going with:
- spin up dockerised tofnd, spin up dockerised axelar node.
- All the test suites run against this setup [0% done cuz I don't have a test suite yet]
- put 2 evm chains on each side of axelar to simulate behaviour we want [0% done, but I've done setups like this before]

**Comment by ctoyan** [comment]
Closing. Please read [this comment](https://eig3r.slack.com/archives/C06A2QAPE2Z/p1709241551957549?thread_ts=1709198951.020469&cid=C06A2QAPE2Z) on slack.
